# Generated by Django 3.1.1 on 2020-09-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aixxuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='useratt', to='aixxuser.axxuser', verbose_name='收藏者id')),
                ('usered', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='useredatt', to='aixxuser.axxuser', verbose_name='被收藏者id')),
            ],
            options={
                'db_table': 't_attention',
            },
        ),
    ]
