# Generated by Django 3.1.1 on 2020-09-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('reg_time', models.DateTimeField(blank=True, null=True)),
                ('alipay_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qq_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wx_user_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'axx_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='访问的用户')),
                ('func_name', models.CharField(max_length=100, verbose_name='功能名')),
                ('func_args', models.CharField(blank=True, max_length=100, null=True, verbose_name='参数1')),
                ('func_kwargs', models.CharField(blank=True, max_length=200, null=True, verbose_name='参数2')),
                ('content', models.TextField(blank=True, null=True, verbose_name='响应的结果')),
                ('error_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='异常编码')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='异常信息')),
                ('ip_address', models.CharField(max_length=300, verbose_name='客户端id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('path', models.CharField(blank=True, max_length=100, null=True, verbose_name='请求地址')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='状态码')),
            ],
            options={
                'db_table': 't_logger',
            },
        ),
        migrations.CreateModel(
            name='ScoreConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='执行的动作')),
                ('score', models.IntegerField(verbose_name='赠送的积分数')),
                ('status', models.BooleanField(default=True, verbose_name='是否开启功能')),
            ],
            options={
                'db_table': 't_score_conf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=100, verbose_name='积分来源')),
                ('score', models.IntegerField(verbose_name='积分数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='积分获取时间')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scores', to='aixxuser.axxuser')),
            ],
            options={
                'db_table': 't_user_score',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AxxUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('realname', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo')),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('axxuser', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='axxuser', to='aixxuser.axxuser')),
            ],
            options={
                'db_table': 'axx_user_info',
                'managed': True,
            },
        ),
    ]
